name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
          cache: true

      - name: Run Go Vet
        run: go vet ./...

      - name: Check Go Format
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "The following files are not formatted correctly. Please run 'go fmt ./...':"
            gofmt -l .
            exit 1
          fi

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
          cache: true

      - name: Run Tests
        run: CGO_ENABLED=0 go test -v ./pkg/...

  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
          cache: true

      - name: Build Kiwi Client
        run: go build -v -o kiwi ./cmd/kiwi

      - name: Build Kiwi Daemon
        run: go build -v -o kiwid ./cmd/kiwid
